### ISSUE TITLE
Search bar not working in the beta website

### ISSUE THREAD

**Issue by manuelrodgzz** [reactjs/es.react.dev#652]
The console shows the following message: `Invalid Application-ID or API key`

<img width="315" alt="image" src="https://user-images.githubusercontent.com/56905268/229915965-d0b8a52f-15da-474c-95fa-8225406102ce.png">

**Comment by carburo** [comment]
Yeah, the beta website has yet to be completely set up. The original website is now out of beta, and the React team is working to do the same for the translation websites. We'll check again once the work is completed.

**Comment by mateoguzmana** [comment]
Can we close this one? The docs are not in Beta anymore and the search bar seems to be working.
