### ISSUE TITLE
Not Found Error

### ISSUE THREAD

**Issue by AlainCarmona** [reactjs/es.react.dev#749]
A No Found Error appears opening https://es.react.dev/learn/add-react-to-a-website

Something similar for https://[raw.githubusercontent.com/reactjs/reactjs.org/main/static/html/single-file-example.html](https://raw.githubusercontent.com/reactjs/reactjs.org/main/static/html/single-file-example.html)

**Comment by mateoguzmana** [comment]
Thanks for reporting the bug! I've updated the broken links in #750
