### ISSUE TITLE
link Not Found

### ISSUE THREAD

**Issue by alopezgo** [reactjs/es.react.dev#866]
Hi, Im reading documentation in https://es.react.dev/learn/add-react-to-a-website but the paragraph below Add React to HTML' s link (https://es.react.dev/learn/add-react-to-a-website) is NOT FOUND

Regards

**Comment by rickhanlonii** [comment]
Moved to the https://github.com/reactjs/es.react.dev repo.

**Comment by mateoguzmana** [comment]
Thanks for reporting! we've fixed this issue already.

![image](https://github.com/reactjs/es.react.dev/assets/20783123/20eaffe6-de42-4487-a1c0-73ad820b2aca)
