### ISSUE TITLE
"How to add React to an HTML page" does not exist.

### ISSUE THREAD

**Issue by LautaroCepeda-Developer** [reactjs/es.react.dev#867]
https://es.react.dev/learn/add-react-to-a-website

![image](https://user-images.githubusercontent.com/123782531/235243703-e4c28d77-ee0d-47ef-a76d-764cd0dcd4a3.png)

**Comment by rickhanlonii** [comment]
Transferred to the es.react.dev repo.

**Comment by mateoguzmana** [comment]
Thanks for reporting! we've fixed this issue already

![image](https://github.com/reactjs/es.react.dev/assets/20783123/d15bef90-d209-497a-b88d-b1fba52b1885)
