### ISSUE TITLE
Traducción de "React DOM Hooks"

### ISSUE THREAD

**Issue by carburo** [reactjs/es.react.dev#883]
Artículo a traducir: [`src/content/reference/react-dom/hooks/index.md`](https://github.com/reactjs/es.react.dev/blob/main/src/content/reference/react-dom/hooks/index.md)

[Chequea la guía de traducción para más información](https://github.com/reactjs/es.react.dev/blob/main/TRANSLATION.md)

**Comment by gurjott** [comment]
please assign me

**Comment by 0xJaskeerat** [comment]
Hey @carburo , can you give a lil more detail what result are you expecting from this 
It would be easy to understand through a nice description

**Comment by carburo** [comment]
Hola @0xJaskeerat, he añadido un enlace con más información.
