### ISSUE TITLE
Traducción de la referencia de  "useFormStatus"

### ISSUE THREAD

**Issue by carburo** [reactjs/es.react.dev#884]
Artículo a traducir: [`src/content/reference/react-dom/hooks/useFormStatus.md`](https://github.com/reactjs/es.react.dev/blob/main/src/content/reference/react-dom/hooks/useFormStatus.md)

[Chequea la guía de traducción para más información](https://github.com/reactjs/es.react.dev/blob/main/TRANSLATION.md)

**Comment by gurjot03** [comment]
por favor asigname

**Comment by gurjot03** [comment]
por favor combine la solicitud de extracción
