### ISSUE TITLE
[Typo]: Error tipográfico en useCallback

### ISSUE THREAD

**Issue by JordiCasasPla** [reactjs/es.react.dev#951]
### Summary

<img width="883" alt="image" src="https://github.com/user-attachments/assets/082388f5-ec33-42ce-8565-c9ca41895e2d">

### Page

https://es.react.dev/reference/react/useCallback

### Details

Example: In useCallback should say:  **_cada vez_** insted of **_cada ves_**

**Comment by JordiCasasPla** [comment]
Me gustaría contribuir directamente y realizar esta corrección en la documentación. ¿Podría asignárseme esta issue para hacer el cambio?

**Comment by carburo** [comment]
¡Hola! Para este tipo de correcciones puedes crear un PR directamente sin necesidad de abrir un _issue_.
